"""Focused persistence ports consumed by recruiting use cases.

The protocols deliberately describe business-specific queries.  They do not
offer a generic CRUD surface and do not expose an ORM session.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, List, Protocol

from app.ai.contracts import ModelRequest, ModelResponse


class RepositoryConflictError(Exception):
    """A persistence uniqueness conflict safe for application handling."""


class IdentityRepository(Protocol):
    def find_user_by_email(self, email: str) -> Any | None: ...
    def get_user(self, user_id: str, tenant_id: str) -> Any | None: ...
    def get_tenant(self, tenant_id: str) -> Any | None: ...
    def add_tenant_admin(self, tenant_name: str, email: str, password_hash: str) -> Any: ...


class FeedbackRepository(Protocol):
    def get_result(self, tenant_id: str, result_id: str) -> Any | None: ...
    def get_job_version(self, tenant_id: str, version_id: str) -> Any | None: ...
    def add(self, feedback: Any) -> None: ...


class JobRepository(Protocol):
    def list_templates(self) -> list[Any]: ...
    def get(self, tenant_id: str, job_id: str) -> Any | None: ...
    def list(self, tenant_id: str) -> list[Any]: ...
    def add(self, job: Any) -> None: ...
    def list_versions_for_tenant(self, tenant_id: str) -> List[Any]: ...
    def reload(self, tenant_id: str, job_id: str) -> Any | None: ...


class KnowledgeRepository(Protocol):
    def get_document(self, tenant_id: str, document_id: str, *, for_update: bool = False) -> Any | None: ...
    def by_checksum(self, tenant_id: str, checksum: str, document_type: str) -> Any | None: ...
    def list_documents(self, tenant_id: str) -> list[Any]: ...
    def deactivate(self, document: Any) -> None: ...
    def add(self, document: Any) -> None: ...
    def reload_document(self, tenant_id: str, document_id: str) -> Any | None: ...


class MatchingRepository(Protocol):
    def get_succeeded_resume(self, tenant_id: str, resume_id: str) -> Any | None: ...
    def active_jobs(self, tenant_id: str) -> list[Any]: ...
    def add_run(self, run: Any) -> None: ...
    def get_run(self, tenant_id: str, run_id: str) -> Any | None: ...
    def latest_for_resume(self, tenant_id: str, resume_id: str) -> Any | None: ...


class ResumeRepository(Protocol):
    def get(
        self,
        tenant_id: str,
        resume_id: str,
        include_deleted: bool = False,
        *,
        for_update: bool = False,
    ) -> Any | None: ...
    def find_by_hash(self, tenant_id: str, sha256: str) -> Any | None: ...
    def list(self, tenant_id: str) -> list[Any]: ...
    def list_succeeded(self, tenant_id: str) -> List[Any]: ...
    def add(self, resume: Any) -> None: ...
    def reload(self, tenant_id: str, resume_id: str) -> Any | None: ...
    def scrub_private_data(self, tenant_id: str, resume: Any, deleted_at: datetime) -> None: ...


class ModelTraceRepository(Protocol):
    def succeeded(
        self,
        tenant_id: str,
        business_type: str,
        business_id: str,
        source_ids: list[str],
        request: ModelRequest,
        response: ModelResponse,
        fallback_reason: str | None = None,
    ) -> Any: ...

    def failed(
        self,
        tenant_id: str,
        business_type: str,
        business_id: str,
        source_ids: list[str],
        request: ModelRequest,
        error: Any,
        latency_ms: float,
    ) -> Any: ...
